# Generated by Django 5.1.3 on 2025-03-01 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_phone_number_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('objectives', models.TextField()),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('tech', 'Technologie'), ('health', 'Santé'), ('agriculture', 'Agriculture'), ('education', 'Éducation'), ('other', 'Autre')], max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='projects/docs/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepreneur', models.ForeignKey(limit_choices_to={'role': 'entrepreneur'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
