# Generated by Django 5.1.3 on 2025-03-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_amount_raised_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amount_raised',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
