# Generated by Django 5.1.7 on 2025-03-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_amount_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amount_collected',
        ),
    ]
