# Generated by Django 5.2 on 2025-04-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_project_amount_collected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='date_invested',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='investment',
            name='payer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='service',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='transaction_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
